### ISSUE TITLE
Output CVE on finding issues

### ISSUE THREAD

**Issue by ronanbrowne** [snyk-tech-services/snyk-delta#161]
Hi, 

When flagging a vulnerability found is there a flag we can pass to also out put the CVE or CVSS score as this would be helpful when identifying if immediate action is needed or not?

As it stands snyk-delta just outputs the severity level and upgrade path if available.

**Comment by aarlaud** [comment]
Ack. Will take a look

**Comment by aarlaud** [comment]
Alright, took forever, apologies, but I've added the cvssScore in the output in https://github.com/snyk-tech-services/snyk-delta/pull/179. I can't quite put the CVE as many vulns don't have a CVE, but all of them do have a cvss score. hopefully that works for you.
