### ISSUE TITLE
using deprecated project issues API

### ISSUE THREAD

**Issue by scott-es** [snyk-tech-services/snyk-delta#49]
https://snyk.docs.apiary.io/#reference/projects/project-issues/list-all-issues-deprecated

need to move to https://snyk.docs.apiary.io/#reference/projects/aggregated-project-issues/list-all-aggregated-issues

**Comment by aarlaud** [comment]
yes, planned work next sprint.

**Comment by aarlaud** [comment]
closing as this was completed.
